BIND_HOST = "0.0.0.0"
SENSORS_PORT = 5020
ACTUATORS_PORT = 5021
SIMULATION_PORT = 5022
DEVICE_ID = 1

SCAN_INTERVAL_S = 0.5

SENSOR_REG_LEVEL = 0
SENSOR_REG_INLET_FLOW = 1
SENSOR_REG_OUTLET_FLOW = 2
SENSOR_REG_PUMP_CONFIRMED = 3
SENSOR_REG_EMERGENCY_STOP = 4
SENSOR_REG_PUMP_SPEED = 5
SENSOR_REGISTER_COUNT = 6

ACTUATOR_REG_PUMP_RUN = 0
ACTUATOR_REG_PUMP_SPEED_SETPOINT = 1
ACTUATOR_REG_VALVE_OPEN = 2
ACTUATOR_REGISTER_COUNT = 3

SIM_REG_FAULT_PUMP_FAILED = 0
SIM_REG_FAULT_CABLE_CUT = 1
SIM_REG_FAULT_SHORT_CIRCUIT = 2
SIM_REG_FAULT_CONTACTOR_NO_CONFIRM = 3
SIM_REG_FAULT_EMERGENCY_STOP = 4
SIM_REG_CLEAR_FAULTS = 5
SIM_REG_FORCE_LEVEL_L = 6
SIM_REG_FORCE_LEVEL_TRIGGER = 7
SIM_HOLDING_COUNT = 8

SIM_REG_REAL_LEVEL_X10 = 0
SIM_REG_REAL_INLET_FLOW_X10 = 1
SIM_REG_REAL_OUTLET_FLOW_X10 = 2
SIM_REG_OVERFLOW_FLOW_X10 = 3
SIM_REG_REAL_PUMP_SPEED = 4
SIM_REG_PUMP_CONFIRMED = 5
SIM_REG_CMD_PUMP_RUN = 6
SIM_REG_CMD_PUMP_SPEED_SETPOINT = 7
SIM_REG_CMD_VALVE_OPEN = 8
SIM_REG_ACTIVE_FAULTS = 9
SIM_REG_LEVEL_SIGNAL = 10
SIM_INPUT_COUNT = 11
SIM_REGISTER_MAX = 32767

MA_MIN = 4.0
MA_MAX = 20.0
MA_CABLE_CUT = 0.0
MA_SHORT_CIRCUIT = 22.0
MA_REGISTER_MAX = 25.0
MA_REGISTER_SCALE = 100

LEVEL_RANGE_L = (0.0, 1000.0)
FLOW_RANGE_LPM = (0.0, 150.0)
PCT_RANGE = (0.0, 100.0)

TANK_CAPACITY_L = 1000.0
INITIAL_LEVEL_L = 500.0

PUMP_MAX_FLOW_LPM = 120.0
PUMP_SPEED_RAMP = 0.25
PUMP_MIN_SPEED_PCT = 15.0

VALVE_MAX_FLOW_LPM = 90.0
VALVE_FLOW_LEVEL_EXPONENT = 0.5

CONTACTOR_CONFIRM_DELAY_S = 0.5
OVERFLOW_LEVEL_L = 950.0
